echoCTF/echoCTF.RED

frontend/controllers/SiteController.php, frontend/models/forms/ResetPasswordForm.php
=> Autologin on passwd reset

.scrutinizer.yml, frontend/actions/ActionColumn.php, frontend/composer.json, frontend/controllers/DashboardController.php, frontend/models/forms/ResetPasswordForm.php, frontend/themes/material/layouts/main.php, frontend/themes/material/modules/target/views/default/claim.php, frontend/themes/material/site/error.php, frontend/widgets/Noti.php, frontend/widgets/target/views/target.php
eliminate some dependencies that we have included already on our codebase
=> eliminate some dependencies

backend/modules/gameplay/models/Badge.php
=> ensure points is cast as int

backend/migrations/m200518_111954_add_location_suggestion_solution_columns_to_treasure_table.php, backend/modules/gameplay/models/Treasure.php, backend/modules/gameplay/views/treasure/_form.php, backend/modules/gameplay/views/treasure/view.php, backend/modules/restapi/controllers/TreasureController.php, frontend/models/Player.php, frontend/themes/material/modules/target/views/default/_versus.php
Work towards providing some more details to players
=> Work towards providing some more details to players

backend/migrations-red/m200520_115034_disable_timer_for_tutorials.php, backend/migrations/m200520_100945_add_timer_column_to_target_table.php, backend/modules/gameplay/models/Target.php, backend/modules/gameplay/models/TargetSearch.php, backend/modules/gameplay/views/target/_form.php, backend/modules/gameplay/views/target/index.php, backend/modules/gameplay/views/target/view.php, frontend/models/Stream.php, frontend/modules/target/controllers/DefaultController.php, frontend/themes/material/modules/target/views/default/_versus.php
Fixes #114 
Fixes #110 
Fixes #104 
Fixes #108
=> Timer improvements

backend/modules/frontend/views/player/_form.php
=> Change status into drop down list

schemas/echoCTF-triggers.sql
=> Add trigger to remove player_finding memcache keys for deleted records

backend/migrations-red/m200603_144142_cleanup_old_notifications.php, backend/modules/activity/views/notification/index.php, frontend/actions/profile/NotificationsRestAction.php, frontend/models/Notification.php, frontend/models/Player.php, schemas/echoCTF-events.sql
* remove old notifications
* ensure initial player notifications have `created_at` and `updated_at` value
* create daily event to remove notifications that are older than 7 days
issue #122
=> notification related updates

frontend/themes/material/modules/target/views/default/_versus.php, frontend/themes/material/modules/target/views/default/index.php, frontend/web/css/material.css
=> changes to make the IP more visible on target/view

backend/modules/activity/views/notification/_form.php
Add group by first letter and order by name on backend notification/create dropdown list
=> Add group by first letter and order by name on backend notifications

backend/modules/activity/views/player-vs-target/index.php
Fix player-progress dropdown menu to include each character only once fixes #170
=> Fix backend player-progress

frontend/themes/material/site/index.php
ensure link rel="cannonical" and meta property="og:url" have a value on 
frontpage
=> make sure we include proper url on site/index

frontend/themes/material/modules/target/views/default/_versus.php, frontend/widgets/target/views/target.php
=> move spin on target/view

backend/migrations-red/m200904_160510_update_badges_and_add_new_badges.php, frontend/models/Player.php, frontend/themes/material/profile/_card.php, frontend/themes/material/profile/_profile_settings.php, frontend/themes/material/profile/index.php, frontend/themes/material/site/login.php, frontend/web/css/material.css, themes/cards/iconic/card.css, themes/cards/iconic/card.html
This is still a wip issue #177
=> added iconic cards on and updated profile badge listing

backend/modules/activity/controllers/ChallengeSolverController.php, backend/modules/activity/controllers/PlayerTargetHelpController.php, backend/modules/activity/controllers/WriteupController.php, backend/modules/activity/models/ChallengeSolver.php, backend/modules/activity/models/PlayerTargetHelp.php, backend/modules/activity/models/Writeup.php, backend/modules/gameplay/controllers/TutorialTargetController.php, backend/modules/gameplay/controllers/TutorialTaskController.php, backend/modules/gameplay/controllers/TutorialTaskDependencyController.php, frontend/actions/ActionColumn.php, frontend/modules/target/models/PlayerTargetHelp.php, frontend/modules/target/models/Writeup.php
=> replace all className() => class

backend/modules/gameplay/views/target/view.php
=> add example on target view so users can copy/paste easier

frontend/components/BaseController.php, frontend/controllers/DashboardController.php, frontend/controllers/ProfileController.php, frontend/controllers/SiteController.php, frontend/modules/challenge/controllers/DefaultController.php, frontend/modules/game/controllers/DefaultController.php, frontend/modules/game/controllers/LeaderboardsController.php, frontend/modules/help/controllers/FaqController.php, frontend/modules/help/controllers/InstructionController.php, frontend/modules/help/controllers/RuleController.php, frontend/modules/network/controllers/DefaultController.php, frontend/modules/target/controllers/DefaultController.php, frontend/modules/target/controllers/WriteupController.php, frontend/modules/team/controllers/DefaultController.php, frontend/modules/tutorial/controllers/DefaultController.php, frontend/themes/material/layouts/header.php
=> base Accessrule filters

docs/frontend-actions.md, frontend/components/PlayerEvents.php, frontend/controllers/ProfileController.php, frontend/mail/emailChangeVerify-html.php, frontend/mail/emailChangeVerify-text.php, frontend/models/Player.php, frontend/models/PlayerAR.php, frontend/models/forms/SettingsForm.php, frontend/models/forms/VerifyEmailForm.php, frontend/themes/material/profile/_account_settings.php, frontend/themes/material/profile/_profile_settings.php, frontend/themes/material/profile/settings.php
=> Change status on new email

backend/migrations/m210112_211428_create_tbi_headshot_trigger.php, backend/migrations/m210114_095633_add_first_column_to_challenge_solver_table.php, backend/migrations/m210114_095711_create_tbi_challenge_solver_trigger.php, backend/migrations/m210114_121019_alter_rating_default_value_on_challenge_solver_table.php, backend/modules/activity/models/ChallengeSolver.php, backend/modules/activity/models/ChallengeSolverSearch.php, backend/modules/activity/views/challenge-solver/_form.php, backend/modules/activity/views/challenge-solver/index.php, backend/modules/activity/views/challenge-solver/view.php, frontend/commands/GeneratorController.php, frontend/components/Img.php, frontend/config/web.php, frontend/models/Profile.php, frontend/modules/challenge/controllers/DefaultController.php, frontend/modules/challenge/models/ChallengeSolver.php, frontend/modules/game/controllers/DefaultController.php, frontend/modules/game/models/Headshot.php, frontend/themes/material/modules/challenge/views/default/view.php, frontend/themes/material/modules/target/views/default/_versus.php, frontend/themes/material/profile/index.php, frontend/widgets/vote/VoteWidget.php, frontend/widgets/vote/views/_vote.php
=> Add first challenge solver

frontend/config/web.php, frontend/models/Menu.php, frontend/modules/help/controllers/DefaultController.php, frontend/themes/material/modules/help/views/default/index.php
=> add central landing page for available help

frontend/controllers/DashboardController.php, frontend/themes/material/dashboard/index.php, frontend/web/js/material-dashboard.js
=> [WIP] Dashboard retouch

backend/modules/gameplay/controllers/TargetController.php, backend/modules/gameplay/views/target/generate.php, backend/modules/gameplay/views/target/index.php, backend/modules/gameplay/views/target/view.php
=> Generate target buildfiles

docs/Console-Commands.md, docs/console-commands/Generator.md
Add some more info regarding the frontend generator command
=> Generator docs

backend/migrations/m210427_135745_add_weight_column_to_target_table.php, backend/modules/gameplay/models/TargetAR.php, backend/modules/gameplay/views/target/_form.php, backend/modules/gameplay/views/target/index.php, backend/modules/gameplay/views/target/view.php, frontend/modules/target/models/TargetAR.php
This will allow us to order as we like the available target list
=> add weight column to target table.

backend/modules/gameplay/controllers/TargetController.php, backend/modules/gameplay/views/target/status.php
Initial status pull through the API
=> initial get status implementation

frontend/components/Img.php, frontend/controllers/ProfileController.php
=> add try/catch on img so that we dont crash

frontend/components/Sysconfig.php
=> Add per-instance caching of memcached keys and prefetch of keys

ansible/Dockerfiles/example/variables.yml, ansible/playbooks/feed-targets.yml, backend/modules/restapi/controllers/TargetMetadataController.php, frontend/themes/material/modules/target/views/default/_target_description.php, frontend/themes/material/modules/target/views/default/_target_metadata.php
hook metadata to the playbooks and frontend
=> Hook metadata

backend/migrations/m211230_134128_update_tai_url_route_trigger.php, backend/migrations/m211230_134133_update_tau_url_route_trigger.php, backend/migrations/m211230_134134_update_tad_url_route_trigger.php, backend/modules/frontend/controllers/TeamplayerController.php, backend/modules/frontend/views/teamplayer/index.php, frontend/modules/team/controllers/DefaultController.php, frontend/modules/team/models/Team.php, frontend/themes/material/modules/team/views/default/_team_card.php, frontend/themes/material/modules/team/views/default/index.php, frontend/themes/material/modules/team/views/default/invite.php, frontend/themes/material/modules/team/views/default/view.php, frontend/web/css/material.css
team cleanups and improvements
=> Team cleanups

backend/modules/frontend/controllers/PlayerController.php, backend/modules/frontend/views/player/ovpn.php, backend/modules/frontend/views/profile/view_full.php
=> add ovpn view, action and quick actions menu on profile

ansible/templates/nginx.conf.j2, frontend/web/429.html, frontend/web/500.html, frontend/web/501.html, frontend/web/504.html, frontend/web/505.html
These changes make our error pages much better and allow us to handle all types of expected and unexpected errors.
fixes #581 
supplementary reading https://gist.github.com/proditis/b446a15bd481b1ff96dc91fdf0171211
=> Error pages and nginx

backend/commands/CronController.php
so that we know what is going on
fixes #571
=> display a few extra errors

backend/modules/settings/controllers/SysconfigController.php
=> redirect to the new key if changed

frontend/widgets/captcha/CaptchaAction.php
=> regenerate captcha on every submit

contrib/findingsd-federated.sql, contrib/findingsd.sql
=> dont use the same variable names as our columns

backend/modules/activity/controllers/PlayerCounterNfController.php, backend/modules/activity/views/player-counter-nf/update.php, backend/modules/activity/views/player-counter-nf/view.php
=> use player_id,metric for the operations

backend/migrations/m220511_213708_update_tau_player_last_trigger_with_memcache.php, contrib/findingsd-federated.sql
=> Fixes issue 617

ansible/runonce/vpngw.yml
reorder some tasks to allow offline setups
update some openvpn command line args
=> fix broken variables

frontend/modules/network/controllers/DefaultController.php
This pr fixes ordering on the networks target listing
=> add sort order on network view

backend/commands/SslController.php, backend/migrations/m220521_205918_alter_player_ssl_table_drop_column_txtcrt.php, backend/migrations/m220521_210518_update_tau_player_ssl_trigger_remove_txtcrt_column.php, backend/migrations/m220521_210953_alter_crl_table_drop_column_txtcrt.php, backend/modules/frontend/models/Crl.php, backend/modules/frontend/models/CrlSearch.php, backend/modules/frontend/models/PlayerSsl.php, backend/modules/frontend/models/PlayerSslSearch.php, backend/modules/frontend/views/crl/_form.php, backend/modules/frontend/views/crl/_search.php, backend/modules/frontend/views/crl/index.php, backend/modules/frontend/views/crl/view.php, backend/modules/frontend/views/player-ssl/_form.php, backend/modules/frontend/views/player-ssl/_search.php, backend/modules/frontend/views/player-ssl/view.php, frontend/models/PlayerSsl.php
=> Remove ssl txtcrt field

frontend/web/css/material.css, frontend/widgets/target/views/target.php
this pr makes the table columns consistent across reloads and page changes
=> target table size consistencies

backend/commands/TargetController.php, backend/migrations/m220530_213836_update_tai_headshot_trigger_schedule_ondemand.php, backend/modules/infrastructure/views/target/index.php, backend/views/layouts/main.php, backend/views/site/index.php
=> Server time and other small fixes

ansible/templates/pf.conf.j2, ansible/templates/vpn.service.conf.j2, backend/commands/CronController.php, backend/modules/infrastructure/models/TargetInstance.php, backend/modules/infrastructure/views/target-ondemand/view.php, contrib/findingsd-federated.sql
if a user of a private instance is online and the instance isnt pending any action update the updated_at field
fixes #634
=> improve private instance timeout

backend/commands/CronController.php, backend/modules/gameplay/models/Finding.php
=> add support for min/max pflog interfaces

backend/migrations/m220607_093340_create_time_headshot_with_player.php, backend/migrations/m220607_103806_update_tau_headshot_trigger_timer_avg.php, frontend/modules/challenge/models/ChallengeSolverQuery.php, frontend/themes/material/profile/_challenge_solves.php
This PR fixes the headshot after update trigger to also sync the averages
=> Headshot tau

backend/modules/frontend/controllers/ProfileController.php, backend/modules/frontend/views/profile/_player_memcache_details.php, backend/modules/frontend/views/profile/index.php, frontend/config/web.php
This PR does
* Add IP setting of player from frontend
* Display the player IP on the backend profile view
* Make profiles with validation errors better visible on backend profile listing 
* Rename approve_avatar to approve-avatar action
* Introduce an action "clear-validation" that resets fields that fail validation criteria
=> Backend player views

frontend/modules/target/actions/SpawnRestAction.php
This PR allows to disable individual target spawn route for everyone
=> check if the action is disabled for this target

frontend/themes/material/modules/target/views/default/_target_card.php, frontend/widgets/target/views/target.php
This PR fixes #656 by syncing the IP displayed on title and target card
=> sync the display of target IP on title

backend/modules/infrastructure/controllers/TargetStateController.php, backend/modules/infrastructure/models/TargetState.php, backend/modules/infrastructure/models/TargetStateQuery.php, backend/modules/infrastructure/models/TargetStateSearch.php, backend/modules/infrastructure/views/target-state/_form.php, backend/modules/infrastructure/views/target-state/_search.php, backend/modules/infrastructure/views/target-state/create.php, backend/modules/infrastructure/views/target-state/index.php, backend/modules/infrastructure/views/target-state/update.php, backend/modules/infrastructure/views/target-state/view.php, backend/views/layouts/main.php
Add target state manipulation from the backend
=> Add target state manipulation from the backend

ansible/runonce/includes/chroot_env.yml, ansible/runonce/includes/selfsigned.yml, ansible/runonce/mui.yml, ansible/runonce/pui.yml, ansible/runonce/vpngw.yml
Minor fixes that we missed for openbsd 7.1
=> Runonce fixes

docker-compose-novpn-macvlan.yml, docker-compose-novpn.yml, docker-compose.yml
change the `hostname` to `IP` for the DB
fixes #676
=> this change is a workaround for issue #676

contrib/Dockerfile, contrib/Dockerfile-backend, contrib/Dockerfile-frontend, contrib/Dockerfile-mariadb, contrib/Dockerfile-vpn
* add tini
* buster => bullseye
* composer update
=> Update the containers

backend/modules/frontend/models/Player.php, backend/modules/frontend/views/player/_form.php, backend/modules/frontend/views/player/index.php, docs/Sysconfig-Keys.md, frontend/modules/target/controllers/DefaultController.php
=> Update some academic use in the backend

docs/Sysconfig-Keys.md, frontend/controllers/DashboardController.php, frontend/widgets/stream/StreamWidget.php
This PR adds support for configurable academic grouping. This allows us to activate the feature and its inherent performance hit on demand.
=> Academic grouping flag

backend/modules/gameplay/models/TargetVariable.php
=> fixes #680

.github/workflows/ci-tests.yml, backend/commands/TemplateController.php, backend/components/Mailer.php, backend/composer.json, backend/config/console.php, backend/config/web.php, backend/mail/layouts/activation.php, backend/mail/layouts/gmail.php, backend/mail/layouts/text.php, docs/DOCKER-COMPOSE-NOVPN.md, docs/INSTALL-LINUX.md, docs/INSTALL.md
issue #508 for the backend
also fixes #684
=> Issue 508 mui

frontend/components/validators/HourRegistrationValidator.php, frontend/components/validators/StopForumSpamValidator.php, frontend/components/validators/TotalRegistrationsValidator.php
on fields that their validator is disabled from sysconfig dont inject the js validation
=> dont inject js validation

docs/Sysconfig-Keys.md, frontend/modules/target/controllers/DefaultController.php
=> add new sysconfig flag target_guest_view_deny

frontend/themes/material/modules/network/views/default/_network.php
=> show the button even when there are no subscriptions

docs/INSTALL-LINUX.md, docs/INSTALL.md, docs/VPN-SERVER.md
=> include some missing steps

ansible/runonce/pui.yml, ansible/runonce/vpngw.yml
also create backend/frontend executable symlinks, fixes #732
=> update playbook crontabs

ansible/runonce/mui.yml
=> seems that it was missing only from mui playbook

frontend/models/Stream.php
=> remove double ,

ansible/Dockerfiles/sanitycheck/Dockerfile, ansible/Dockerfiles/sanitycheck/autoregister.yml, ansible/Dockerfiles/sanitycheck/variables.yml, ansible/inventories/challenges/host_vars/sanitycheck.yml
=> Sanitychecks

backend/modules/activity/controllers/TargetPlayerStateController.php, backend/modules/activity/models/TargetPlayerState.php, backend/modules/activity/models/TargetPlayerStateQuery.php, backend/modules/activity/models/TargetPlayerStateSearch.php, backend/modules/activity/views/target-player-state/_form.php, backend/modules/activity/views/target-player-state/_search.php, backend/modules/activity/views/target-player-state/create.php, backend/modules/activity/views/target-player-state/index.php, backend/modules/activity/views/target-player-state/update.php, backend/modules/activity/views/target-player-state/view.php, backend/views/layouts/main.php
=> Add target player state

frontend/themes/material/modules/team/views/default/_team_card.php
Remove number_format from team cards as it confuses the translation
=> Remove number format from team cards for points, it breaks the translations

ansible/runonce/mui.yml, ansible/runonce/vpngw.yml
=> create cli commands for backend

backend/components/BaseController.php, backend/modelscli/BannedMxServer.php, backend/modelscli/BannedMxServerQuery.php, backend/modelscli/EmailTemplate.php, backend/modelscli/EmailTemplateQuery.php, backend/modelscli/EmailTemplateSearch.php, backend/modelscli/VpnTemplate.php, backend/modelscli/VpnTemplateQuery.php, backend/modelscli/VpnTemplateSearch.php, backend/modules/frontend/controllers/PlayerController.php
This PR makes the downloading of player OVPN files behave the same on backend as it does on frontend. 
Fixes #711
=> Backend ovpn dl

backend/migrations/m230107_123003_add_category_column_to_notification_table.php, backend/modules/activity/controllers/NotificationController.php, backend/modules/activity/models/Notification.php, backend/modules/activity/models/NotificationSearch.php, backend/modules/activity/views/notification/_form.php, backend/modules/activity/views/notification/index.php, backend/modules/activity/views/notification/view.php, frontend/assets/MaterialAsset.php, frontend/models/Notification.php, frontend/models/NotificationQuery.php, frontend/web/js/libechoctf.js, frontend/web/js/material-dashboard.js, frontend/widgets/NotificationsWidget.php
This PR 
* fixes #223 
* fixes #692
=> Notification types and counters update

backend/migrations/m230107_232912_add_index_to_archived_and_category_columns_on_notification.php, backend/modules/infrastructure/views/target-instance/index.php, frontend/models/NotificationQuery.php, frontend/modules/api/Module.php, frontend/modules/api/controllers/NotificationController.php, frontend/themes/material/modules/target/views/default/view.php, frontend/web/js/libechoctf.js, frontend/widgets/NotificationsWidget.php
This PR closes one of the items of issue #630 
It provides live updates for
=> Short polling notifications

.github/workflows/ci-merged-pull_requests.yml, .github/workflows/ci-pull_requests.yml, .github/workflows/ci-tests.yml
update workflows to use **`checkout@v3`** instead of `checkout@v2`
=> use checkout@v3 on our workflows

backend/views/site/index.php
Fixes #796 for backend dashboard
=> fix indentation and escape username

backend/commands/PlayerController.php, backend/modules/frontend/controllers/PlayerController.php, backend/modules/frontend/controllers/ProfileController.php, backend/modules/frontend/views/player/fail-validation.php, backend/modules/frontend/views/player/help/fail-validation.php, backend/modules/frontend/views/player/index.php, backend/modules/frontend/views/profile/fail-validation.php, backend/modules/frontend/views/profile/help/fail-validation.php, docs/console-commands/Player.md
This PR introduces some validation improvements for the backend.
Adding player and profile fail validation pages
=> Validation pages

backend/commands/CronController.php, backend/commands/TargetController.php, backend/composer.json, backend/modules/activity/views/writeup/index.php, backend/modules/infrastructure/views/target-instance/index.php, backend/web/css/site.css, docs/console-commands/Target.md, frontend/composer.json
Add operations to destroy private instances and on demand targets
=> Discard private instances

backend/commands/MigrationController.php, backend/modules/activity/models/Headshot.php, backend/modules/activity/views/headshot/index.php, backend/modules/gameplay/models/Target.php, backend/modules/infrastructure/views/target/index.php, docs/Sysconfig-Keys.md, frontend/modules/game/controllers/LeaderboardsController.php, frontend/modules/game/models/PlayerScoreMonthly.php, frontend/modules/game/models/PlayerScoreMonthlyQuery.php, frontend/themes/material/modules/game/views/leaderboards/_ordinal_score.php, frontend/themes/material/modules/game/views/leaderboards/index.php
Add a monthly leaderboard into the mix
fixes #551
=> Monthly leaderboard

backend/commands/PlayerController.php, docs/console-commands/Frontend_Validator.md, frontend/commands/ValidatorController.php
This PR makes minor improvements to the frotnend validator cli command:
* Adds team-avatars and player-avatars commands
* Documents the cli command
* fixes #807
=> Improve frontend validator command

backend/modules/activity/models/WriteupRatingSearch.php
=> fixes #813

frontend/assets/MaterialAsset.php, frontend/modules/subscription/Module.php, frontend/modules/subscription/controllers/DefaultController.php, frontend/modules/subscription/models/ProductQuery.php, frontend/modules/subscription/views/default/_create.php, frontend/modules/subscription/views/default/_product.php, frontend/modules/subscription/views/default/pricing.css, frontend/web/css/material.css
Add a stripe customer portal link on players that have a valid stripe_id assigned
=> Stripe portal link

backend/modules/sales/commands/CronController.php, docs/console-commands/Sales.md
Adds individual products and prices import cli command `backend sales/stripe-import-products`
=> Add products import

frontend/modules/game/controllers/LeaderboardsController.php, frontend/modules/target/models/Writeup.php, frontend/modules/target/models/WriteupQuery.php, frontend/themes/material/modules/game/views/leaderboards/_most_headshot.php, frontend/themes/material/modules/game/views/leaderboards/_most_writeup.php, frontend/themes/material/modules/game/views/leaderboards/index.php, frontend/themes/material/modules/target/views/default/_target_card.php, frontend/themes/material/profile/_card.php, frontend/web/css/material.css
=> Leaderboard additions

backend/commands/TargetController.php, backend/modules/sales/controllers/ProductController.php, backend/modules/sales/models/PlayerSubscription.php, backend/modules/sales/models/Price.php, backend/modules/sales/views/price/_form.php
This PR 
* makes target/destroy-ondemand to ignore heartbeat so that it can destroy ondemand even when not expired
* make sure we dont fail with vip products that have no prices 
* backend price create add default metadata value
* Introduce product/ajax-search and hook on price form
=> Minor post release bugs

backend/modules/frontend/controllers/ProfileController.php, backend/modules/frontend/views/profile/_activated_writeups.php, backend/modules/frontend/views/profile/view_full.php
=> add activated-writeups action and view

frontend/components/DisabledRoute.php
=> repair the logic to match only on given user

backend/migrations/m230131_174555_create_credits_table.php, backend/modules/content/controllers/CreditsController.php, backend/modules/content/models/Credits.php, backend/modules/content/models/CreditsSearch.php, backend/modules/content/views/credits/_form.php, backend/modules/content/views/credits/_search.php, backend/modules/content/views/credits/create.php, backend/modules/content/views/credits/help/create.php, backend/modules/content/views/credits/help/index.php, backend/modules/content/views/credits/help/update.php, backend/modules/content/views/credits/index.php, backend/modules/content/views/credits/update.php, backend/modules/content/views/credits/view.php, backend/modules/settings/models/Experience.php, backend/views/layouts/main.php, frontend/commands/GeneratorController.php, frontend/modules/help/controllers/CreditsController.php, frontend/modules/help/models/Credits.php, frontend/modules/network/controllers/DefaultController.php, frontend/themes/material/modules/help/views/credits/_item.php, frontend/themes/material/modules/help/views/credits/index.php, frontend/themes/material/modules/help/views/credits/style.css, frontend/themes/material/modules/help/views/default/index.php
=> Credits pages

docs/INSTALL-LINUX.md
forgot to create a standalone branch for that
=> updated default mysql auth command & some slight md tweaks

backend/modules/activity/models/ChallengeSolverSearch.php, backend/modules/activity/models/HeadshotSearch.php, backend/modules/activity/models/NotificationSearch.php, backend/modules/activity/models/PlayerBadgeSearch.php, backend/modules/activity/models/PlayerFindingSearch.php, backend/modules/activity/models/PlayerTargetHelpSearch.php, backend/modules/activity/models/WriteupRatingSearch.php
=> add created_at partial search

backend/modules/frontend/controllers/PlayerController.php, backend/modules/frontend/controllers/ProfileController.php, backend/modules/frontend/views/player-last/index.php, backend/modules/frontend/views/player/fail-validation.php, backend/modules/frontend/views/profile/index.php
* Introduce clear-verification-token action on backend  player controller
* Fix order for activated writeups to include target name
* Add link to player profile from player last gridview
* Display field that failed validation on backend player/fail-validation
* Add action set-seleted to backend player controller and hook action to player fail-validation view
* update the `Fail validation` buttons to have the same color
=> multiple minor fixes

backend/migrations/m230203_223558_update_tai_headshot_trigger_private_instances.php
dont schedule a spin for private instances
=> update headshot trigger spin conditions

frontend/themes/material/dashboard/_news_item.php, frontend/themes/material/dashboard/_target_instance_card.php, frontend/themes/material/dashboard/_top.php
=> Private instances dashboard

ansible/runonce/mui.yml, ansible/runonce/pui.yml
=> add letencrypt configuration

backend/composer.json, frontend/commands/GeneratorController.php, frontend/themes/material/modules/target/views/default/_target_card.php, frontend/themes/material/modules/target/views/default/view.php, frontend/themes/material/modules/target/views/writeup/read.php
=> Target card fixes

backend/commands/PlayerController.php, backend/modules/frontend/views/profile/view_full.php
* improve backend player/check-dupips operations
* point to proper link for delete on player/profile/full
=> minor fixes to player cli and backend

backend/migrations/m230224_103953_update_tad_player_trigger_to_clean_scores.php
to delete monthly score and counter_nf records also
=> update tad_player trigger

frontend/modules/subscription/models/Product.php, frontend/modules/subscription/views/default/_product.php
=> Fix subscriptions from firefox

frontend/themes/material/modules/target/views/default/search.php
there is no need we do this when the dropdown select gets hidden
fixes #897
=> dont clear when dropdown hides

frontend/themes/material/modules/target/views/default/_target_card.php
=> make default non zero IP copy to clipboard

backend/modules/infrastructure/views/network-target-schedule/_form.php, backend/widgets/sleifer/autocompleteAjax/AutocompleteAjax.php
=> Update autocomplete ajax widget

frontend/components/BaseController.php
The following PR fixes a bug on our BaseController beforeAction method which under certain conditions caused it to allow the view of pages that shouldnt be visible.
=> fix beforeAction bug when csrfValidation failed

backend/modules/frontend/views/profile/_heading.php, backend/views/site/index.php
=> Backend fixes

frontend/overloads/yii/filters/AccessControl.php
comment out the redirect functionality for now until we have time to test extensively
=> comment out this functionality for now

docs/Sysconfig-Keys.md, frontend/config/web.php, frontend/controllers/SiteController.php, frontend/themes/material/site/maintenance.php
This PR introduces Maintenance mode on the frontend application. When the **`maintenance`** sysconfig key is set to 1 the system will catchAll requests and render a static html file (if exists `@app/web/dt.html`) or a default maintenance view.
=> Maintenance mode

frontend/controllers/ProfileController.php
Respect visibility but use try/catch to ensure empty content.
fixes #921
=> wrap everything into a try/catch

backend/modules/activity/models/SpinHistorySearch.php, backend/modules/activity/views/spin-history/index.php, backend/modules/frontend/views/profile/_spin_history.php, backend/modules/infrastructure/views/target/full-view/_spin_history.php
=> Spin history relation

ansible/runonce/docker-servers.yml, ansible/templates/docker-server-advanced.yml, ansible/templates/docker-server-template.yml
These changes make docker-servers.yml a bit more robust to errors and configuration changes. Furthermore we can re-run the playbook as many times as we want on top of servers that we had it run in the past and bring them up to specifications.
=> Docker servers playbook update

backend/commands/CronController.php
=> dont spin ondemand targets rather pull them

contrib/Dockerfile-mariadb, contrib/Dockerfile-vpn, contrib/entrypoint-vpn.sh, contrib/findingsd.pl, contrib/findingsd.sql, contrib/supervisord.conf
=> Update docker containers

backend/commands/CronController.php, backend/modules/infrastructure/models/DockerContainer.php, contrib/Dockerfile-vpn, frontend/themes/material/layouts/left.php
Avoid throwing exception for foreach from command line cron/instances command
=> Avoid throwing exception for foreach from command line cron/instances command

frontend/themes/material/profile/_card.php
fix logic bug on profile card, only show subscription button when all_player_vip is not true
=> again logic bug

contrib/Dockerfile-backend, contrib/Dockerfile-frontend, contrib/Dockerfile-vpn, contrib/supervisord.conf
=> add cron to packages

backend/modules/frontend/views/player/index.php, backend/modules/frontend/views/profile/_heading.php, backend/modules/frontend/views/profile/view_full.php, frontend/config/db-local.php
The following PR does the following
* Makes player actions on the backend dynamic depending on player state
* Improve profile full view on backend to display echoCTF profile url
* Remove `enableParamLogging` from the frontend default db-local.php since it seems to break things
=> Minor improvements

backend/README.md, docs/API.md, docs/ARCHITECTURE.md, docs/DOCKER-COMPOSE.md, docs/DOCKER-REGISTRY.md, docs/INSTALL-LINUX.md, docs/INSTALL.md, docs/Localization.md, docs/Network-Visuals.md, docs/Onsite-Infrastructure.md, docs/Participants-Tutorial.md, docs/Sysconfig-Keys.md, docs/VPN-SERVER.md, docs/ansible/DOCKER-TARGETS.md, docs/console-commands/Cron.md, docs/index.md, frontend/README.md
The following PR contains:
- Updated dead links
- Formatting improvements
- Added more insight about `docker-compose.yml` port mapping
=> Some documentation tweaks

backend/migrations-init/m231101_181919_add_default_rules.php, backend/migrations-init/m231101_181938_add_default_instructions.php, backend/migrations-init/m231101_182034_add_default_faq.php, backend/migrations/m231101_205544_add_unique_to_title_faq.php
This PR :
* fixes #1018 
* fixes #1003
=> Add default entries for FAQ, Rules and Instructions

frontend/modules/network/Module.php, frontend/modules/network/models/Network.php, frontend/modules/target/Module.php, frontend/themes/material/modules/network/views/default/_network.php
Only show subscribe button to networks that are part of subscription products.
fixes #952
=> Only show subscribe button to networks that are part of subscription products

backend/modules/infrastructure/models/TargetMetadataSearch.php, backend/modules/infrastructure/views/target-metadata/index.php
=> fixes #998

backend/modules/settings/models/ConfigureForm.php, backend/modules/settings/views/sysconfig/configure.php
=> Update configure form with more settings

frontend/controllers/SiteController.php, frontend/models/Player.php, frontend/models/forms/SignupForm.php, frontend/models/forms/VerifyEmailForm.php
fixes #980 
fixes #979
fixes #977
=> improve require_activation=false

backend/migrations/m231103_205532_add_created_at_and_updated_at_column_to_target_player_state_table.php, backend/migrations/m231104_191348_update_tai_player_treasure_add_created_and_updated_at_to_state.php, backend/migrations/m231104_191359_update_tai_player_finding_add_created_and_updated_at_to_state.php, backend/migrations/m231104_223328_update_target_player_state_created_at_and_updated_at.php, backend/modules/activity/models/TargetPlayerStateSearch.php, backend/modules/activity/views/target-player-state/index.php
add updated_at/created_at fields to target_player_state and populate the fields 
fixes #933
=> add updated_at/created_at fields to target_player_state

contrib/findingsd-federated.sql
without this team instances fail to be queried
=> add team_allowed field on target_instance

frontend/themes/material/modules/team/views/default/view.php
was only showed instances if team_visible_instances is true
=> fix team instances logic bug

backend/modules/frontend/views/profile/_heading.php, frontend/models/forms/VerifyEmailForm.php
* Dont display badge on backend when viewing non active players
* Generate player badge when they first join
=> Player badge improvements

docs/Sysconfig-Keys.md, frontend/modules/subscription/controllers/DefaultController.php
=> make automatic_tax configurable

backend/modules/gameplay/models/Challenge.php, backend/modules/gameplay/models/Question.php, docs/Sysconfig-Keys.md, frontend/config/web.php
Force HTTPS & add default value and range for player_type of challenge/question
=> Force HTTPS & add default value and range for player_type of challenge/question

ansible/ansible.cfg
make ansible a bit less verbose
=> make ansible runs a bit more silent

frontend/models/Profile.php
=> replace curly braces

ansible/runonce/db.yml, ansible/runonce/docker-registry.yml, ansible/runonce/docker-servers.yml, ansible/runonce/mui.yml, ansible/runonce/pui.yml, ansible/runonce/vpngw.yml, ansible/templates/docker-server-advanced.yml, ansible/templates/unbound.conf.j2
This PR fixes and improves some of the ansible playbooks for the initial server setups
=> Playbook fixes

contrib/echoctf_updown_mysql.sh
Fix a logical bug that allowed non approved players to see and team instances
=> fix team instances logical bug 

frontend/components/echoCTFView.php, frontend/themes/material/layouts/main.php
it appears that the order variables and files are loaded has changed (either in Yii or PHP) and these overrides didnt seem to be working properly.
The following fix ensures the overrides are loaded properly. 
Fixes #1103
=> Fix layout overrides

backend/commands/MetadataController.php, backend/commands/TargetController.php, backend/views/console/metadata/view.php, docs/console-commands/Metadata.md
Introduce CLI commands for metadata manipulation
Fixes #1114
=> Cli metadata commands

backend/modules/gameplay/controllers/ChallengeController.php, backend/modules/gameplay/models/Challenge.php, backend/modules/settings/models/ConfigureForm.php, backend/modules/settings/views/sysconfig/configure.php, docs/Sysconfig-Keys.md, frontend/themes/material/modules/challenge/views/default/view.php
Handle challenge fileuploads better
* If there is no filename use the challenge id
* if filename is given use the filename to rename the uploaded file
* add trim validator for filename on Challenge model
* Hook challenge_home and challenge_root into the sysconfig
* Properly use the values of challenge_home and challenge_root
=> Handle challenge fileuploads better

backend/commands/VpnController.php, backend/components/OpenVPN.php, backend/components/validators/VerifymailValidator.php, backend/migrations/m240320_235210_add_server_column_to_openvpn_table.php, backend/migrations/m240320_235211_alter_openvpn_table_unique_keys.php, backend/modules/activity/models/PlayerLast.php, backend/modules/frontend/controllers/PlayerController.php, backend/modules/frontend/models/PlayerAR.php, backend/modules/frontend/views/player/index.php, backend/modules/settings/models/ConfigureForm.php, backend/modules/settings/models/Openvpn.php, backend/modules/settings/views/openvpn/_form.php, backend/modules/settings/views/openvpn/index.php, backend/modules/settings/views/openvpn/view.php, contrib/Dockerfile-backend, contrib/Dockerfile-vpn, contrib/entrypoint-vpn.sh, docs/Sysconfig-Keys.md, docs/console-commands/Vpn.md, frontend/commands/ValidatorController.php, frontend/components/validators/VerifymailValidator.php, frontend/models/forms/SignupForm.php, frontend/modules/game/controllers/LeaderboardsController.php, frontend/themes/material/layouts/left.php
This PR includes the following
* Improved backend/frontend/player/index gridview
* add a new sysconfig `hide_timezone`, causes the timezone information to be hidden from the frontend
* add a new sysconfig `guest_visible_leaderboards` to enable/disable access to the leaderboards by guest users (fixes #1119)
* Improved `backend/yii vpn` commands documentation, error handling and operations 
* fixes #1130 
* fixes #1129
* Updated vpn docker entrypoint script to perform a `backend/yii vpn/load` on the existing configuration file
* Introduce verifymail.io fixes #1116
=> Multiple improvements and fixes from dev environment

frontend/themes/material/modules/target/views/default/index.php, frontend/web/css/material.css, frontend/web/js/material-dashboard.js, frontend/widgets/target/TargetWidget.php, frontend/widgets/target/TargetWidgetAsset.php, frontend/widgets/target/views/target.php
The following PR:
* fixes #1144 
* fixes #1142
=> Tooltip fixes

backend/migrations/m240418_224927_update_existing_discord_link_entries.php, backend/modules/content/controllers/DefaultController.php, backend/modules/content/views/default/help/menu-items.php, backend/modules/content/views/default/menu_items.php, backend/modules/settings/models/ConfigureForm.php, backend/modules/settings/views/sysconfig/configure.php, backend/views/layouts/main.php, docs/Sysconfig-Keys.md, frontend/widgets/Menu.php
=> Issue 1151

ansible/runonce/db.yml, contrib/mysql-events-checker.sh
=> Issue 1152

frontend/modules/challenge/models/AnswerForm.php, frontend/themes/material/modules/challenge/views/default/_question.php
=> Issue 1134

backend/migrations-init/m211204_005430_load_default_email_templates.php, backend/migrations/m240502_232532_add_approval_column_to_player_table.php, backend/modules/frontend/actions/player/MailAction.php, backend/modules/frontend/controllers/PlayerController.php, backend/modules/frontend/models/PlayerAR.php, backend/modules/frontend/models/PlayerSearch.php, backend/modules/frontend/views/player/index.php, backend/modules/frontend/views/profile/_heading.php, backend/modules/frontend/views/profile/_quick_actions.php, backend/modules/frontend/views/profile/view_full.php
Introduce player approval status and streamline the process of player registration approval/rejection.
=> Player approval status and process

backend/modules/frontend/actions/player/MailAction.php, backend/modules/frontend/controllers/PlayerController.php, backend/modules/frontend/views/player/index.php, backend/modules/frontend/views/profile/_quick_actions.php, docs/Sysconfig-Keys.md
=> mass rename players_require_approval into player_require_approval

backend/migrations/m240506_091812_create_player_metadata_table.php, backend/migrations/m240506_093953_drop_affiliation_column_from_player_table.php, backend/modules/activity/controllers/TeamScoreController.php, backend/modules/frontend/controllers/PlayerMetadataController.php, backend/modules/frontend/models/PlayerAR.php, backend/modules/frontend/models/PlayerMetadata.php, backend/modules/frontend/models/PlayerMetadataQuery.php, backend/modules/frontend/models/PlayerMetadataSearch.php, backend/modules/frontend/models/PlayerSearch.php, backend/modules/frontend/views/player-metadata/_form.php, backend/modules/frontend/views/player-metadata/_search.php, backend/modules/frontend/views/player-metadata/create.php, backend/modules/frontend/views/player-metadata/help/create.php, backend/modules/frontend/views/player-metadata/help/index.php, backend/modules/frontend/views/player-metadata/help/update.php, backend/modules/frontend/views/player-metadata/index.php, backend/modules/frontend/views/player-metadata/update.php, backend/modules/frontend/views/player-metadata/view.php, backend/modules/frontend/views/player/_form.php, backend/modules/frontend/views/player/index.php, backend/modules/frontend/views/player/view.php, backend/modules/frontend/views/profile/_heading.php, backend/modules/settings/models/ConfigureForm.php, backend/modules/settings/views/sysconfig/configure.php, backend/views/layouts/main.php
=> Player metadata and configuration

backend/modules/infrastructure/controllers/TargetController.php, backend/modules/infrastructure/views/target/full-view.php, backend/modules/infrastructure/views/target/full-view/_heading.php, backend/modules/infrastructure/views/target/full-view/_metadata-tab.php, backend/modules/infrastructure/views/target/full-view/_network-schedule-tab.php, backend/modules/infrastructure/views/target/full-view/_target_details.php, backend/modules/infrastructure/views/target/full-view/_target_instances-tab.php
=> Target datails

frontend/themes/material/profile/_card.php
=> fixes #1075

ansible/playbooks/feed-targets.yml, ansible/runonce/docker-registry.yml, ansible/runonce/docker-servers.yml, ansible/runonce/mui.yml, ansible/runonce/pui.yml, ansible/runonce/vpngw.yml, backend/commands/SslController.php, backend/modules/content/views/default/menu_items.php, backend/modules/frontend/controllers/ProfileController.php, backend/views/layouts/main.php, contrib/init.sh, docs/Sysconfig-Keys.md, docs/console-commands/Vpn.md, frontend/models/PlayerAR.php, frontend/models/PlayerMetadata.php, frontend/models/PlayerMetadataQuery.php, frontend/models/PlayerMetadataSearch.php, frontend/widgets/Card.php
This PR 
* Updates ansible playbooks for latest openbsd
* Updates vpn crl handling
* Adds metadata relation to the player model
* Minor backend profile and menu crashes
=> Ansible and metadata

backend/commands/VpnController.php, backend/migrations/m241016_190515_update_tai_writeup_trigger.php, backend/modules/frontend/models/PlayerAR.php, backend/modules/infrastructure/controllers/TargetOndemandController.php, backend/views/site/index.php, contrib/findingsd-federated.sql, contrib/verify-cn.sh, frontend/models/PlayerAR.php, frontend/models/Profile.php, frontend/models/forms/SettingsForm.php, frontend/modules/target/controllers/WriteupController.php, frontend/themes/material/dashboard/_news_item.php, frontend/themes/material/modules/team/views/default/_team_card.php, frontend/themes/material/modules/team/views/default/view.php
=> Closing some of the issues

backend/modules/activity/models/Stream.php, backend/modules/frontend/models/Profile.php
=> update target and profile links to ensure they work on backend

ansible/runonce/docker-registry.yml, ansible/runonce/pui.yml, ansible/runonce/vpngw.yml, ansible/templates/vpn.service.conf.j2, contrib/unbound.conf
=> make sure unbound is configured and run

backend/modules/gameplay/models/Target.php, backend/modules/infrastructure/controllers/TargetController.php, backend/modules/infrastructure/models/TargetInstance.php, backend/modules/infrastructure/views/target-metadata/index.php, backend/modules/settings/models/Sysconfig.php, docs/Sysconfig-Keys.md, frontend/commands/GeneratorController.php
* fixes #1237
* fixes #743
* fixes #974
=> thumbnail and event end notification

docs/Sysconfig-Keys.md, frontend/models/forms/SettingsForm.php, frontend/models/forms/SignupForm.php, frontend/themes/material/profile/_card.php
=> issue #1236

backend/modules/activity/models/Writeup.php
=> add default status of pending on backend

backend/modules/sales/controllers/PlayerSubscriptionController.php, backend/modules/sales/models/PlayerSubscription.php, backend/modules/sales/views/player-subscription/index.php
=> add check local subs against stripe

docs/Sysconfig-Keys.md, frontend/commands/GeneratorController.php, frontend/components/generators/AvatarGenerator.php, frontend/components/generators/Identicon.php, frontend/components/generators/Robohash.php, frontend/composer.json, frontend/models/Player.php, frontend/themes/material/profile/_profile_settings.php
=> Better avatar generation with support for future expansions

frontend/controllers/SiteController.php, frontend/models/Player.php, frontend/models/forms/VerifyEmailForm.php
make sure we generate avatars for every activation
=> make sure we generate avatars for every activation

ansible/runonce/pui.yml, backend/migrations/m241110_214630_from_v0_25_0_to_v1_0_0.php, contrib/Dockerfile-frontend, frontend/config/db-local.php, frontend/models/NotificationQuery.php, frontend/modules/network/models/NetworkTargetScheduleQuery.php, frontend/modules/target/controllers/DefaultController.php, schemas/echoCTF.sql
=> Database optimizations before release

frontend/components/ProfileVisibility.php, frontend/models/PlayerAR.php, frontend/models/Profile.php, frontend/modules/challenge/models/ChallengeSolver.php, frontend/modules/game/models/Headshot.php, frontend/modules/target/controllers/DefaultController.php, frontend/modules/target/models/TargetAR.php, frontend/modules/target/models/TreasureQuery.php, frontend/themes/material/modules/challenge/views/default/view.php, frontend/themes/material/modules/target/views/default/_headshots_card.php, frontend/themes/material/modules/target/views/default/_player_discoveries.php, frontend/themes/material/modules/target/views/default/_versus.php, frontend/widgets/solver/SolverWidget.php, frontend/widgets/solver/views/_card.php, frontend/widgets/target/HeadshotsWidget.php, frontend/widgets/targetcardactions/TargetCardActions.php
=> Limit the amount of queries performed for a single target/view of non guests

backend/modules/frontend/models/PlayerAR.php, backend/modules/frontend/views/profile/view_full.php
=> Dont show tabs with no records for a given player

backend/modules/frontend/models/PlayerSpin.php, backend/modules/frontend/models/PlayerSpinQuery.php, backend/modules/frontend/models/Profile.php, backend/modules/frontend/views/player/_form.php, backend/modules/sales/commands/CronController.php, backend/modules/sales/controllers/PlayerSubscriptionController.php, backend/modules/sales/models/PlayerSubscription.php, backend/modules/sales/models/PlayerSubscriptionQuery.php, backend/modules/sales/views/price/index.php, frontend/modules/subscription/models/Subscription.php
=> Issue 1298

ansible/runonce/pui.yml, docs/Gmail.md, frontend/config/db-local.php, frontend/modules/target/models/Target.php, frontend/widgets/targetcardactions/TargetCardActions.php
* Make sure the pui.yml playbook configures and uses cache
* update db-local to use proper cache settings for people to use
* Improve spinnable methods for Target
* Document using Gmail as a mailing service
=> Minor fixes

frontend/config/web.php
Make our cookies a bit more strict
=> Make our cookies a bit more strict

backend/components/WebhookTrigger.php, backend/modules/content/models/News.php, backend/modules/gameplay/models/Target.php, backend/modules/infrastructure/models/NetworkTargetSchedule.php, frontend/modules/api/models/Target.php
* Fixes #1325 
* Fixes bug where always on machines returned 0 ip
=> Discord and API Target bug fix

frontend/assets/MaterialAsset.php, frontend/modules/target/controllers/DefaultController.php, frontend/themes/material/modules/target/views/default/_target_card.php, frontend/web/js/libechoctf.js
=> Fixes 1324

ansible/runonce/db.yml, ansible/runonce/mui.yml, ansible/runonce/pui.yml, ansible/runonce/vpngw.yml, ansible/templates/acme-client.conf.j2, ansible/templates/nginx.conf.j2, backend/modules/activity/views/spin-queue/_form.php, docs/Initializing a new event.md, docs/Participants-Tutorial.md, docs/Sysconfig-Keys.md, docs/ansible/README.md
* Minor edits on documentation to ensure they render properly from ReadTheDocs
* Minor ansible improvements on clone handling (support branches)
* Minor addition to `ansible/runonce` playbooks for custom network interfaces
=> Documentation and ansible updates

ansible/files/autochromium.desktop, ansible/playbooks/feed-targets.yml, ansible/runonce/db.yml, ansible/runonce/docker-registry.yml, ansible/runonce/docker-servers.yml, ansible/runonce/mui.yml, ansible/runonce/pui.yml, ansible/runonce/vpngw.yml, backend/commands/PlayerController.php, backend/modules/settings/models/Sysconfig.php, frontend/modules/team/controllers/DefaultController.php
This PR does:
* Replace some hardcoded versions with their respective variables
* Update php versions to 8.4
* Add MariaDB Connector C into the build of db, vpn for UDF's to work again
* Fix some logic bugs with installs
* Apply local migrations automatically if the folder exists
=> Latest Ansible playbook updates for OpenBSD 7.7 and minor fixes

backend/modules/settings/models/Openvpn.php, frontend/themes/material/modules/target/views/default/_target_description.php, frontend/themes/material/modules/target/views/default/_target_metadata.php
Improve frontend metadata display a tiny bit and make sure backend openvpn model updates IP's instead of only updating when they are null.
=> Improve frontend metadata display a tiny bit

backend/modules/frontend/actions/player/ExportAction.php, backend/modules/frontend/controllers/PlayerController.php, backend/modules/frontend/views/player/index.php
Add option to export full player details on backend. Needed for events where moderators want to have their user's details
=> Feat export players

backend/commands/MigrateController.php, backend/config/console.php, backend/views/migration/templates/trigger.php, contrib/init.sh
The following PR introduces custom migration templates for our projects. This allows us to create SQL migrations for things that yii2 cant provide. Current we provide migrations for triggers which follow our naming policies and SQL skeleton
=> Custom migration templates introduction

backend/modules/frontend/models/PlayerAR.php, backend/modules/frontend/views/profile/_heading.php
Show if player has a subscription fixes #1392
=> Issue 1392

ansible/runonce/vpngw.yml, contrib/openvpn_tun0.conf, contrib/verify-cn.sh
This enables us to perform real-time validation of the player certificate.
=> add tls-verify

ansible/templates/pf.conf.j2, backend/commands/CronController.php, backend/commands/SslController.php, backend/components/Pf.php, docs/console-commands/Cron.md
* Update PF limits
* Add cron/instance-pf-tables
* Add flush operation to the Pf component
* Add ssl/save-vpn-ta operation
=> Multiple small improvements

backend/commands/VpnController.php, backend/modules/activity/models/Writeup.php, backend/modules/settings/models/Openvpn.php, frontend/models/ProfileAR.php, frontend/models/forms/SettingsForm.php, frontend/modules/target/models/Writeup.php
Replaces `\r\n` to `\n` from:
* Backend vpn command controller
* Backend settings/openvpn
* Profile bio
* Writeup content
Fixes #1400
=> Issue 1400

ansible/runonce/vpngw.yml
=> update arp timeouts

frontend/themes/material/profile/_card.php, frontend/widgets/targetcardactions/TargetCardActions.php
=> Rename spints and restarts to reboot

ansible/runonce/db.yml, backend/modules/frontend/actions/player/ExportAction.php, backend/modules/frontend/models/Team.php, backend/modules/settings/models/Sysconfig.php
=> Small fixes packed into a single PR

backend/modules/frontend/views/profile/_heading.php
=> fixes #1375

docs/Sysconfig-Keys.md, frontend/controllers/DashboardController.php
This PR makes the dashboard graphs visibility configurable
fixes #1315
=> fixes #1315

backend/migrations/m250816_231358_create_player_target_help_after_insert_trigger.php, backend/modules/activity/models/Stream.php, frontend/models/Stream.php
=> Issue 1380

backend/modules/activity/controllers/WriteupController.php, backend/modules/activity/models/WriteupSearch.php, backend/modules/activity/views/writeup/index.php, backend/modules/activity/views/writeup/view.php
=> Issue 1389

backend/modules/sales/commands/CronController.php, backend/modules/sales/controllers/PlayerSubscriptionController.php, backend/modules/sales/models/PlayerSubscription.php, backend/modules/sales/models/PlayerSubscriptionSearch.php, backend/modules/sales/views/player-subscription/index.php
fixes #1399 
* Check and fix backend/modules/sales/commands/CronController.php#L55
=> Issue 1399

ansible/runonce/mui.yml, ansible/runonce/pui.yml, ansible/runonce/vpngw.yml
Ansible logical bugs and improvements
=> Ansible logical bugs and improvements

backend/modules/frontend/controllers/ProfileController.php, backend/modules/frontend/views/profile/_details_tab.php, backend/modules/frontend/views/profile/_vpn_history_ips.php, backend/modules/frontend/views/profile/view_full.php, backend/modules/moderation/models/Abuser.php, backend/modules/moderation/views/abuser/_form.php
=> Issue 1425

frontend/controllers/ProfileController.php, frontend/themes/material/modules/target/views/default/_versus-guest.php, frontend/themes/material/modules/target/views/default/versus.php, frontend/themes/material/profile/guest/index.php, frontend/widgets/leaderboard/Leaderboard.php, frontend/widgets/leaderboard/views/_score.php, frontend/widgets/leaderboard/views/leaderboard.php, frontend/widgets/stream/StreamWidget.php
=> Issue 1351

contrib/sample-migrations/README.md, contrib/sample-migrations/m000000_000001_system_settings.php, contrib/sample-migrations/m000000_000002_update_levels.php, contrib/sample-migrations/m000000_000003_add_extra_docker_servers.php
=> add sample migrations for new events

frontend/modules/target/controllers/DefaultController.php, frontend/themes/material/dashboard/index.php
Limit activity stream displayed records. No need for everything to be visible at all times.
Almost as close as we can logically get for fixes #587
=> Limit activity stream displayed records

backend/modules/frontend/models/Team.php, backend/modules/frontend/views/profile/_heading.php
* Show academic grouping name on backend profile/view-full
* Fix bug in team rank relation of backend Team model
=> Team rank and academic grouping

backend/commands/MigrateController.php, backend/migrations/m250826_155619_create_procedure_repopulate_all_team_streams.php, backend/views/migration/templates/procedure.php, backend/views/migration/templates/routine.php
=> Migration improvements

.markdownlint.yaml, .mkdocs.yml, ansible/ssh_config, docs/DOCKER-SERVERS.md, docs/Getting-Started.md, docs/ansible/DOCKER-REGISTRY.md, docs/ansible/README.md, docs/index.md
Attempt to improve ansible documentation
=> Improve ansible documentation

ansible/inventories/dockers/group_vars/all.yml, ansible/inventories/dockers/host_vars/docker100.yml, ansible/inventories/dockers/hosts, ansible/inventories/servers/group_vars/all.yml, ansible/inventories/servers/group_vars/vpn.yml, ansible/inventories/servers/host_vars/registry.yml, ansible/runonce/docker-registry.yml, ansible/runonce/vpngw.yml, docs/Sysconfig-Keys.md, docs/ansible/DOCKER-REGISTRY.md
=> Ansible and doc improvements

backend/modules/activity/models/TeamStream.php, backend/modules/activity/models/TeamStreamQuery.php, backend/modules/frontend/views/team/view.php, backend/modules/infrastructure/models/TargetInstanceSearch.php, backend/modules/infrastructure/views/target-instance/index.php, backend/modules/infrastructure/views/target/full-view.php
=> Issue 1464

backend/migrations/m250903_210652_add_player_id_column_to_team_stream_table.php, backend/migrations/m250903_211309_update_trigger_after_insert_on_stream.php, backend/migrations/m250903_211650_update_procedure_repopulate_team_stream.php, backend/migrations/m250903_213807_perform_team_repopulation.php, backend/migrations/m250903_214032_update_trigger_after_delete_on_stream.php, backend/modules/activity/models/TeamStreamAR.php, backend/modules/frontend/controllers/PlayerController.php, backend/modules/frontend/views/profile/_quick_actions.php, backend/modules/frontend/views/team/view.php, backend/modules/infrastructure/views/target/full-view.php, frontend/models/PlayerAR.php, frontend/modules/team/controllers/DefaultController.php, frontend/modules/team/models/TeamStream.php, frontend/modules/team/models/TeamStreamQuery.php, frontend/themes/material/modules/team/views/default/_team_card.php, frontend/themes/material/modules/team/views/default/view.php
* Fixes #1470
* Fixes #1460
* Updates frontend team card to show contributes points of the player to the team instead of individual ones
* Fixes #1462 as well as on profile view
=> Team Stream updates

README.md, ansible/examples/default-settings.yml, backend/commands/CronController.php, backend/migrations/m250914_084533_update_trigger_after_update_on_player_last_table.php, backend/migrations/m250914_091828_create_procedure_get_player_networks.php, backend/modules/activity/controllers/TeamScoreController.php, backend/modules/activity/models/PlayerLast.php, backend/modules/frontend/controllers/PlayerController.php, backend/modules/frontend/controllers/TeamController.php, backend/modules/frontend/controllers/TeamplayerController.php, backend/modules/infrastructure/models/TargetInstanceAuditQuery.php, backend/modules/infrastructure/models/TargetInstanceQuery.php, contrib/echoctf_updown_mysql.sh, contrib/findingsd-federated.sql, docs/Miscellaneous.md, docs/ansible/DB.md, docs/ansible/README.md
work towards simplifying the connect script and its firewall rules
* Fixes #1397
* Fixes #1483
* Update README.md, ansible docs and comment ansible playbooks
* Use last record ID on actionInstancePf
* Use approvedMembers instead of teamPlayers relation for Team module
* refactor `tau_player_last` trigger
* add `get_player_pf_networks` on VPN and backend
* refactor LOGIN/LOGOUT vpn sql operations
* Make toggle academic operations cover all the `academic_grouping` values with `($model->academic + 1) % Yii::$app->sys->academic_grouping`
* Add `latestPerPlayerInstance` and `since` Target Instance Query method
* refactor `echoctf_updown_mysql.sh`
=> Openvpn connect improvement

backend/commands/CronController.php, backend/modules/infrastructure/models/TargetInstance.php, backend/modules/settings/models/ConfigureForm.php, backend/modules/settings/models/Sysconfig.php, backend/modules/settings/views/sysconfig/configure.php, docs/Sysconfig-Keys.md
This PR does the following:
* Introduces the `stripe_webhookLocalEndpoint` url key to manage the secret URL of the stripe webhook requests
* Create getFindings method on TargetInstance to bring only the pending findings for the player of this instance (fixes #1319)
* Fixes #1352 - Pf::allowToNetwork does this and its called from our cron command `active_targets_pf` private method
=> Findings and Sysconfig updates

ansible/files/pf.conf, ansible/files/pui.service.conf, ansible/files/vpn.service.conf, backend/modules/settings/models/ConfigureForm.php, backend/modules/settings/views/sysconfig/configure.php, docs/DOCKER-SERVERS.md, frontend/widgets/targetcardactions/TargetCardActions.php
* Add `dashboard_graph_visible` & `disable_ondemand_operations`
* Add `venue` table on the pf templates
* Fix documentation mentioning `DOCKER_REGISTRY` as string
=> minor fixes to configuration form and documentation

backend/migrations/m250921_104021_delete_unused_sysconfig_keys.php, backend/modules/settings/models/ConfigureForm.php, backend/modules/settings/views/sysconfig/configure.php
Add a few more extra keys into the mix and remove some unused ones.
=> add a few more keys missing from sysconfig

backend/commands/CronController.php, backend/modules/infrastructure/models/TargetInstance.php, contrib/multi-ports.py
* Fix issue with encrypted flags on targets without environment variables on backend
* Make multi-ports use stderr for application messages and stdout for parser (ie logstalgia, gource)
=> Minor fixes from tests
