echoCTF/echoCTF.RED

docs/API.md
frontend/modules/api/Module.php
frontend/modules/api/controllers/HeadshotController.php
frontend/modules/api/models/Headshot.php
frontend/modules/api/models/HeadshotQuery.php
frontend/modules/api/models/HeadshotSearch.php
frontend/modules/game/models/Headshot.php

Implement a basic headshots REST endpoint for people to query. The endpoint is available on `api/headshot/index` with UrlRules exposing it under `api/headshots`
* The collection envelope is called `items` 
* Every item has the following fields 
* `profile_id: integer` The player profile id
* target_id: integer The target id
* target_name: string The target name
* timer: integer The time in seconds for completion
* first: boolean If the headshot was first
* rating: integer The user provided difficulty rating for the target
* created_at: datatime The headshot was achieved
example
```json
{
"profile_id":"177952",
"target_id":24,
"target_name":"tweek",
"timer":26740,
"first":false,
"rating":-1,
"created_at":"2020-09-11 04:15:47"
}
```
The endpoint supports:
* filtering through …

Headshots api endpoint

---

contrib/mysql-init.sql
docker-compose-novpn-macvlan.yml
docker-compose-novpn.yml
docker-compose.yml

also add a trick of `USE information_schema;` as first command of the 
mysql-init.sql to ensure we switch to its internal encoding.
fixes #568

start mysql with character set and collation

---

frontend/themes/material/profile/_headshot_item.php
frontend/themes/material/profile/_headshots.php

This PR fixes 
* the average text being displayed when there is no average
* the headshot timer line when timer is 0
This was reported by @fmarasoglou :pray:

Fix profile average

---

docs/console-commands/Generator.md
frontend/commands/GeneratorController.php
frontend/components/DisabledRoute.php
frontend/extensions/MemcacheUrlManagerBootstrap.php

Routes local file caching

---

frontend/components/BaseController.php
frontend/controllers/SiteController.php

This PR replaces some error pages with redirects and UI notifications to make the experience less scary for the users

Improve error pages

---

backend/modules/sales/controllers/PlayerCustomerController.php
frontend/modules/subscription/models/Customer.php

This PR fixes a bug where the `existsOnStripe` check was returning "true" causing subscriptions to fail

Subscriptions bug

---

docs/Sysconfig-Keys.md
frontend/modules/target/models/TargetQuery.php

The following PR:
* introduces the sysconfig key `target_hide_inactive`
* updates the TargetQuery to include `active=1` when the key is active
fixes #753

Introduce the ability to hide inactive targets from the frontend

---

backend/migrations/m221215_212831_update_tai_sysconfig_serialize_json_all.php
backend/migrations/m221215_212839_update_tad_sysconfig_serialize_json_all.php
backend/migrations/m221215_212842_update_tau_sysconfig_serialize_json_all.php
backend/migrations/m221215_214626_update_populate_memcache_procedure_include_serialized_sysconfig.php
frontend/components/Sysconfig.php

This PR introduces a new sysconfig key `sysconfig_json` (notice it is not prefixed) which includes all the sysconfig keys json encoded. There are a few keys excluded due to size considerations. These keys are **`CA*`, `disabled_routes`, `frontpage_scenario`, `routes`, `writeup_rules`, `vpn-ta.key`**
On some local preliminary tests, the pho execution time of each page did not exceed 39-40ms for processing and sending data (the css and js files still add up but not when they are cached)
fixes #717

Json encode all sysconfig keys

---

backend/migrations/m221219_213856_add_announce_column_to_network_table.php
backend/modules/gameplay/models/Network.php
backend/modules/gameplay/models/NetworkSearch.php
backend/modules/gameplay/models/Target.php
backend/modules/infrastructure/models/NetworkTargetSchedule.php
backend/modules/infrastructure/views/network/_form.php
backend/modules/infrastructure/views/network/index.php
backend/modules/infrastructure/views/network/view.php

This PR does:
* adds an `announce` column to the network table (for whether or not target additions to it should be announced to news and discord)
* updates the target and network target schedule to respect that when sending news items
* changes the target news message to include `@everyone`

Add unannounced network flag

---

CREDITS.md
backend/modules/activity/controllers/NotificationController.php
backend/modules/activity/controllers/SessionController.php
backend/modules/frontend/actions/player/ImportAction.php
backend/modules/frontend/actions/player/MailAction.php
backend/modules/frontend/controllers/PlayerController.php
backend/modules/frontend/controllers/TeamController.php
backend/modules/frontend/models/PlayerAR.php
backend/modules/gameplay/controllers/ChallengeController.php
backend/modules/infrastructure/controllers/TargetController.php
backend/modules/infrastructure/controllers/TargetInstanceAuditController.php
backend/modules/sales/models/PlayerCustomerSearch.php
backend/modules/sales/models/PlayerSubscription.php
backend/modules/sales/models/Product.php

This PR attempts to fix issue #792
Furthermore, the fix is also applied in all backend flash messages by introducing `Html::escape()`

Escape flash messages that receive untrusted input

---

backend/migrations-init/m220102_214745_populate_url_routes.php
backend/migrations/m230109_180919_add_api_notification_url_route.php
frontend/modules/api/controllers/NotificationController.php
frontend/web/js/libechoctf.js

This PR does the following
* Fixes #794
* Forces ajax requests only for notifications
* Adds URL route migrations (that we forgot to add before :man_facepalming: )
* Changes the blur even handling to make it a bit less error prone

only do api GET when Notifications or Hints exist

---

backend/commands/TargetController.php

When PF fails on target-instances we fail to delete the record, make it not be the case

make sure we dont fail when there is no pf table

---

frontend/modules/target/controllers/WriteupController.php
frontend/themes/material/modules/target/views/default/_target_description.php
frontend/themes/material/modules/target/views/default/_target_writeups.php
frontend/themes/material/modules/target/views/default/_versus.php
frontend/themes/material/modules/target/views/writeup/read.php

This PR does the following
* Makes writeups listing available to players even when not active (fixes #823)
* Fail writeup activation when `writeups>=(headshots+2)` (fixes #836)
* Remove the activate writeups link from target description

Writeup Logic modifications

---

backend/migrations/m230307_091159_add_require_findings_column_to_target_table.php
backend/modules/gameplay/models/TargetAR.php
backend/modules/gameplay/models/TargetSearch.php
backend/modules/infrastructure/views/target/_form.php
backend/modules/infrastructure/views/target/index.php
backend/modules/infrastructure/views/target/view.php
docs/Sysconfig-Keys.md
frontend/modules/target/controllers/DefaultController.php
frontend/modules/target/models/TargetAR.php
frontend/modules/target/models/TargetPlayerState.php
frontend/modules/target/models/TargetPlayerStateQuery.php

This PR fixes #837 by introducing
* a sysconfig key `force_findings_to_claim` which forces findings before claim for all targets
* a target boolean column `require_findings` for requiring findings before claiming flags
When a player tries to claim a flag from the _frontend_, the following checks are performed (in addition and after the existing ones)
* If either of `sysconfig:force_findings_to_claim` or `target:require_findings` is **`true`** 
* and the `target_player_state` has no record for the player & target combination
* and the target has findings>0 
* then return an error to the player and increment their `claim_no_finding` counter

Findings before claim

---

backend/modules/gameplay/models/TargetOndemandQuery.php
backend/views/layouts/main.php
backend/views/site/index.php

The following PR does:
* Adds ondemand `powered()` query method
* Adds current infrastructure statistics to the backend dashboard
* Prefixes the main title with the current event name

backend infrastructure dashboard details

---

backend/components/columns/BooleanColumn.php
backend/migrations/m230322_215400_create_rotate_notifications_procedure.php
backend/migrations/m230322_215432_update_rotate_notifications_event.php
backend/modules/activity/controllers/NotificationController.php
backend/modules/activity/views/notification/index.php

The following PR does the following:
* Changes the logic of notification rotations to rotate archived older than 3 hours and non archived ones with regards to targets after 3 days
* Creates a mysql procedure `rotate_notifications` which takes parameters the archived interval and non archived targets interval
* Updates the existing event to call the procedure instead
* Adds a rotate action to backend notifications controller
* Updates the backend notification gridview

Update notification rotation logic and management

---

backend/modules/sales/commands/CronController.php
backend/modules/sales/controllers/PlayerSubscriptionController.php
backend/modules/sales/models/PlayerSubscription.php
backend/modules/sales/models/PlayerSubscriptionQuery.php
backend/modules/sales/views/default/index.php
backend/modules/sales/views/player-subscription/index.php
docs/console-commands/Sales.md
frontend/modules/subscription/models/PlayerSubscription.php

This PR does the following:
* Introduces a static method DeleteInactive to player subscription
* Adds a new vip specific query
* removes networks on subscription cancellation
* Hook delete-inactive console command and web based action

Player subscription cancellation

---

docs/Sysconfig-Keys.md
frontend/assets/MaterialAsset.php
frontend/modules/api/controllers/NotificationController.php
frontend/web/js/libechoctf.js

Introduce maintenance notification for frontend. When `maintenance_notification` is set and has non 0 value, display a SweetAlert about the system going down for maintenance.

Maintenance notification

---

docs/console-commands/Frontend_Generator.md
frontend/commands/GeneratorController.php
frontend/controllers/ProfileController.php
frontend/models/Profile.php

The following PR does the following
fixes #956

Regenerate the player badge when there are updates to the player

---

ansible/runonce/db.yml
ansible/runonce/docker-servers.yml
ansible/runonce/includes/chroot_env.yml
ansible/runonce/mui.yml
ansible/runonce/pui.yml
backend/commands/PlayerController.php
backend/components/Mailer.php
backend/components/validators/HourRegistrationValidator.php
backend/components/validators/LowerRangeValidator copy.php
backend/components/validators/MXServersValidator.php
backend/components/validators/StopForumSpamValidator.php
backend/components/validators/TotalRegistrationsValidator.php
backend/components/validators/WhoisValidator.php
backend/modules/frontend/actions/player/MailAction.php
backend/modules/frontend/models/PlayerAR.php
backend/modules/gameplay/views/finding/_form.php
frontend/components/validators/MXServersValidator.php
frontend/components/validators/StopForumSpamValidator.php
frontend/models/Player.php
frontend/models/forms/SettingsForm.php
frontend/models/forms/SignupForm.php
frontend/modules/subscription/Module.php

Improvements to multiple components

---

ansible/Dockerfiles/example/variables.yml
ansible/Dockerfiles/sanitycheck/variables.yml
ansible/playbooks/feed-targets.yml
docs/DOCKER-REGISTRY.md
docs/ansible/DOCKER-TARGETS.md
frontend/composer.json

Multiple updates to docs and yml

---

backend/web/css/site.css
docs/DOCKER-COMPOSE.md

The following PR does the following:

minor chores

---

backend/components/BaseController.php
backend/modules/frontend/models/Player.php
frontend/components/Img.php
frontend/themes/material/layouts/left.php
frontend/themes/material/modules/target/views/default/_target_card.php

The following PR does the following
* hides VIP badge when `all_players_vip` flag is set
* hides the rank on the player generated badge when the player has no points
* fixes the tooltip of frontend/target/view when target is always on
* adds missing `long` suffix on backend/player/view

Micro corrections

---

contrib/Dockerfile-vpn
contrib/entrypoint-vpn.sh
contrib/mysql-init.sql
contrib/openvpn_tun0.conf
contrib/supervisord.conf
docker-compose-novpn-macvlan.yml
docker-compose-novpn.yml
docker-compose.yml

docker related improvements

---

backend/modules/frontend/views/player/index.php
docs/Sysconfig-Keys.md
frontend/themes/material/profile/_card.php

frontend profile and backend player updates.
Also update the sysconfig documentation

frontend profile and backend player layout updates

---

contrib/Dockerfile-mariadb
docker-compose-novpn-macvlan.yml
docker-compose-novpn.yml
docker-compose.yml
docs/DOCKER-COMPOSE.md

Make sure we dont fail due to mysql-init when we're run for the first time and document the change

make sure we dont fail on brand new startups

---

backend/modules/activity/views/player-finding/_form.php
backend/modules/activity/views/player-treasure/_form.php

make the target dropdown listing ordered alphabetically on player findings and treasures
fixes #1030

make the target dropdown listing ordered alphabetically on player findings and treasures

---

backend/modules/restapi/controllers/FindingController.php
backend/modules/restapi/controllers/TargetMetadataController.php
backend/modules/restapi/controllers/TargetOndemandController.php
backend/modules/restapi/controllers/TreasureController.php

The following PR changes the REST controllers for findings, treasures, target metadata and target ondemand to update existing records instead of throwing error 500 caused by attempting to create new records that are duplicate.
Fixes #1110

dont throw status 500 on duplicate records

---

backend/commands/PlayerController.php
backend/components/BaseController.php
backend/components/Mailer.php
backend/modules/frontend/actions/player/MailAction.php
backend/modules/frontend/models/Player.php
backend/modules/settings/models/ConfigureForm.php
backend/modules/settings/views/sysconfig/configure.php
docs/Sysconfig-Keys.md
frontend/components/Mailer.php
frontend/components/echoCTFView.php
frontend/models/Player.php
frontend/models/forms/PasswordResetRequestForm.php
frontend/models/forms/ResendVerificationEmailForm.php
frontend/models/forms/SettingsForm.php
frontend/models/forms/SignupForm.php

fixes #1167
fixes #1165
fixes #1164

Mail related improvements

---

ansible/runonce/vpngw.yml
backend/components/columns/AcademicColumn.php
backend/migrations/m241027_110007_update_calculate_ranks_procedure_to_make_dynamic.php
backend/migrations/m241027_110150_update_calculate_team_ranks_procedure_to_make_dynamic.php
backend/modules/activity/controllers/NotificationController.php
backend/modules/activity/models/Notification.php
backend/modules/activity/views/notification/_form.php
backend/modules/frontend/views/player/_form.php
backend/modules/frontend/views/team/_form.php
docs/Sysconfig-Keys.md
frontend/controllers/DashboardController.php
frontend/models/Player.php
frontend/modules/help/controllers/CreditsController.php
frontend/modules/target/actions/SpinRestAction.php

* Update vpngw playbook to populate the registry_clients with the common range we're using (10.0.0.0/24)
* Fix dashboard country statistics to only count countries from active players
* fixes #1270
* fixes #1202
* fixes #1269
* fixes #1265
*

Cleaning up some of the issues

---

ansible/Dockerfiles/example/autoregister.yml
ansible/Dockerfiles/example/variables.yml

introduce exec_before_replace flag for cases where we want the exec commands before the replace operations

introduce exec_before_replace flag for cases where we want the exec commands before the replace operations

---

backend/modules/frontend/controllers/PlayerController.php
backend/modules/frontend/controllers/PlayerTokenController.php
frontend/widgets/target/HeadshotsWidget.php

micro fixes

---

ansible/Dockerfiles/example/autoregister.yml
contrib/Dockerfile-frontend
docs/DOCKER-COMPOSE.md

Ensure our docker containers work on non https, by setting the cookie secure into false. 
Fixes the submission error 400 when trying to login after initial setup
issue #1334

Ensure our docker containers work on non https

---

.github/dependabot.yml
backend/composer.json
frontend/composer.json

Try to fix the occasional weekly dependabot failures. For a some time now dependabot fails to perform its check due to errors in php. The problem is that this does not happen all the time but rather it occurs at random times. However when the same checks get initiated manually everything runs smoothly. Hopefully this will reduce the instances that this fail happens.

We now require php >=8

---

contrib/entrypoint-mariadb.sh

Make the user superuser in all cases not just when the `MARIADB_DATABASE` is empty.

grant access to all databases since we use the set global command

---

.github/workflows/ci-merged-pull_requests.yml
.github/workflows/ci-pull_requests.yml
.github/workflows/ci-tests.yml
backend/commands/CronController.php
backend/modules/infrastructure/controllers/TargetInstanceController.php
backend/modules/infrastructure/models/DockerContainer.php

This PR does the following:
* Remove the all-in-one container its not used anywhere
* Fix a logic bug on `cron/instances` which caused `timeout` to become 1second
* Add the docker-server pre-defined network on `cron/instances` and `target-instance/restart`
* Update DockerContainer logic to work with latest docker API changes

Docker updates

---

backend/modules/frontend/controllers/TeamplayerController.php
backend/modules/frontend/views/team/view.php
frontend/modules/team/controllers/DefaultController.php

Team module improvements

---

ansible/runonce/mui.yml
ansible/runonce/pui.yml
ansible/runonce/vpngw.yml
contrib/database_backup.sh

Minor improvements to the runonce playbooks

Playbook improvements

---

contrib/entrypoint-vpn.sh
contrib/openvpn_tun0.conf

* comment out verify-cn by default on openvpn server conf
* parse verify-cn on docker vpn like we did with echoctf_updown_mysql.sh

comment out verify-cn but leave it there.
